[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "day-4"

[[bin]]
name = "day-5"

[[bin]]
name = "day-6"

[[bin]]
name = "day-7"

[[bin]]
name = "day-8"

[[bin]]
name = "day-9"
